
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Home, ChevronRight, ShoppingCart } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import Header from '@/components/header';
import AuthGuard from '@/components/auth/auth-guard';

export default function CreatePurchaseOrderPageContent() {
    const [orderId, setOrderId] = useState('');

    return (
        <AuthGuard>
            <div className="flex flex-col min-h-screen">
                <Header />
                <div className="flex-1 container mx-auto p-4 md:p-8">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
                        <Link href="/" className="flex items-center gap-1 hover:text-foreground">
                            <Home className="w-4 h-4" />
                            Home
                        </Link>
                        <ChevronRight className="w-4 h-4" />
                         <Link href="/purchases" className="hover:text-foreground">
                            Purchases
                        </Link>
                        <ChevronRight className="w-4 h-4" />
                        <span>Create new purchase</span>
                    </div>

                    <div className="flex items-center gap-4 mb-8">
                        <div className="bg-orange-100 dark:bg-orange-900/50 p-3 rounded-lg">
                            <ShoppingCart className="w-6 h-6 text-orange-500" />
                        </div>
                        <div>
                             <p className="text-orange-600 dark:text-orange-400 font-semibold">Purchases</p>
                             <h1 className="text-2xl font-bold">Create new purchase</h1>
                        </div>
                    </div>


                    <div className="max-w-4xl mx-auto">
                        <div className="text-center mb-10">
                            <h2 className="text-2xl font-semibold">All purchases need an order ID.</h2>
                            <p className="text-muted-foreground mt-1">The order ID must be unique. It must be between two and sixty characters. Leading or trailing spaces will be removed.</p>
                        </div>

                        <div className="grid md:grid-cols-2 gap-8 items-center relative">
                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Use next available order ID.</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground">
                                        System order IDs are sequential numbers generated by Finale.
                                    </p>
                                    <p className="text-sm">Next ID: <span className="font-mono">100477</span></p>
                                    <Button className="w-full">Use system order ID</Button>
                                </CardContent>
                            </Card>

                            <div className="relative text-center hidden md:block">
                                <span className="text-muted-foreground font-bold text-lg">OR</span>
                            </div>

                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Enter a unique and valid order ID:</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <Input 
                                        placeholder="e.g., PO-12345" 
                                        value={orderId}
                                        onChange={(e) => setOrderId(e.target.value)}
                                    />
                                    <Button className="w-full" disabled={!orderId.trim()}>Use entered order ID</Button>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </div>
            </div>
        </AuthGuard>
    );
}
