
import { PurchaseOrder, Bill, BillPayment, SalesOrder } from '@/types';

export const mockPurchaseOrders: PurchaseOrder[] = [];

export const mockBills: Bill[] = [];

export const mockBillPayments: BillPayment[] = [];

export const mockSalesOrders: SalesOrder[] = [
  { status: 'Committed', orderDate: '10/24/2025', orderId: '100499', customer: 'Neptune Imports', shipToName: 'Neptune Imports', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Backordered', shipments: '', shipmentsStatusSummary: 'Not packed or shipped', total: 40533.95, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Draft', orderDate: '10/23/2025', orderId: '100495', customer: 'Standard Communications', shipToName: 'Standard Communications', source: 'In-Person', origin: 'Drop Ship', batchId: '', fulfillmentStatus: 'Uncommitted', shipments: '', shipmentsStatusSummary: 'Not packed or shipped', total: 14400.00, invoicesStatusSummary: 'Fully invoiced' },
  { status: 'Committed', orderDate: '10/23/2025', orderId: '100496', customer: 'Zee Wholesale', shipToName: 'Zee Wholesale', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Multiple shipments', shipmentsStatusSummary: 'Fully packed', total: 14967.81, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/23/2025', orderId: '100498', customer: 'Eagle Wholesale', shipToName: 'Eagle Wholesale', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Multiple shipments', shipmentsStatusSummary: 'Fully packed', total: 5610.96, invoicesStatusSummary: 'No Invoice posted' },
  { status: 'Committed', orderDate: '10/22/2025', orderId: '100492', customer: 'Payless Distro', shipToName: 'Payless Distro', source: 'Phone', origin: 'Drop Ship', batchId: '', fulfillmentStatus: 'Backordered', shipments: 'Packed 10/22/2025 (at F...)', shipmentsStatusSummary: 'Partially packed', total: 76050.00, invoicesStatusSummary: 'No Invoice posted' },
  { status: 'Draft', orderDate: '10/22/2025', orderId: '100493', customer: 'Payless Distro', shipToName: 'Payless Distro', source: 'In-Person', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Uncommitted', shipments: '', shipmentsStatusSummary: 'Not packed or shipped', total: 0.00, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/21/2025', orderId: '100484', customer: 'Clutch City Smoke Shop', shipToName: 'Clutch City Smoke Shop', source: 'In-Person', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Packed 10/21/2025 (at M...)', shipmentsStatusSummary: 'Fully packed', total: 934.28, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/21/2025', orderId: '100485', customer: 'SOUTHERN WHOLESAL...', shipToName: 'SOUTHERN WHOLESAL...', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Packed 10/22/2025 (at M...)', shipmentsStatusSummary: 'Fully packed', total: 13839.55, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/20/2025', orderId: '100483', customer: 'Frontline Wholesale Inc', shipToName: 'Frontline Wholesale Inc', source: 'Phone', origin: 'Drop Ship', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Packed 10/20/2025 (at M...)', shipmentsStatusSummary: 'Fully packed', total: 31450.00, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Draft', orderDate: '10/16/2025', orderId: '100478', customer: 'Rave Distro', shipToName: 'Rave Distro', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Uncommitted', shipments: 'Multiple shipments', shipmentsStatusSummary: 'Partially shipped', total: 103357.25, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/14/2025', orderId: '100476', customer: 'AVTX', shipToName: 'AVTX', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Eligible', shipments: '', shipmentsStatusSummary: 'Not packed or shipped', total: 311.77, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/13/2025', orderId: '100474', customer: 'A1 Smoke Kings', shipToName: 'A1 Smoke Kings', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Packed 10/14/2025 (at M...)', shipmentsStatusSummary: 'Fully packed', total: 544.50, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/10/2025', orderId: '100473', customer: 'American Distributors', shipToName: 'American Distributors', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Other error', shipments: 'Multiple shipments', shipmentsStatusSummary: 'Packed w/ exceptions', total: 36389.62, invoicesStatusSummary: 'No Invoice posted' },
  { status: 'Committed', orderDate: '10/9/2025', orderId: '100471', customer: 'HTX Wholesale', shipToName: 'HTX Wholesale', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Multiple shipments', shipmentsStatusSummary: 'Fully packed', total: 2864.50, invoicesStatusSummary: 'No invoice posted' },
  { status: 'Committed', orderDate: '10/9/2025', orderId: '100472', customer: 'Neptune Imports', shipToName: 'Neptune Imports', source: 'Phone', origin: 'Tawakkal Warehouse', batchId: '', fulfillmentStatus: 'Fully packed', shipments: 'Packed 10/10/2025 (at M...)', shipmentsStatusSummary: 'Fully packed', total: 2530.20, invoicesStatusSummary: 'No invoice posted' },
];
