
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Home, ChevronRight, Boxes } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import AuthGuard from '@/components/auth/auth-guard';

export default function CreateProductPageContent() {
    const [productId, setProductId] = useState('');
    const router = useRouter();

    const handleCreateWithSystemId = () => {
        // In a real app, you'd fetch this from a backend service.
        const systemProductId = '100008';
        router.push(`/inventory/products/${systemProductId}`);
    }

    const handleCreateWithEnteredId = () => {
        if (!productId.trim()) return;
        router.push(`/inventory/products/${productId.trim()}`);
    }

    return (
        <AuthGuard>
            <div className="flex flex-col">
                <main className="flex-1 container mx-auto p-4 md:p-8">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
                        <Link href="/" className="flex items-center gap-1 hover:text-foreground">
                            <Home className="w-4 h-4" />
                            Home
                        </Link>
                        <ChevronRight className="w-4 h-4" />
                         <Link href="/inventory/products" className="hover:text-foreground">
                            Products
                        </Link>
                        <ChevronRight className="w-4 h-4" />
                        <span>Create new product</span>
                    </div>

                    <div className="flex items-center gap-4 mb-8">
                        <div className="bg-blue-100 dark:bg-blue-900/50 p-3 rounded-lg">
                            <Boxes className="w-6 h-6 text-blue-500" />
                        </div>
                        <div>
                             <p className="text-blue-600 dark:text-blue-400 font-semibold">Products</p>
                             <h1 className="text-2xl font-bold">Create new product</h1>
                        </div>
                    </div>


                    <div className="max-w-4xl mx-auto">
                        <div className="text-center mb-10">
                            <h2 className="text-2xl font-semibold">All products need a product ID.</h2>
                            <p className="text-muted-foreground mt-1 max-w-2xl mx-auto">The product ID must be unique. It must be between two and 191 characters. Leading or trailing spaces will be removed. A product lookup will also be created with the same id referencing the newly created product.</p>
                        </div>

                        <div className="grid md:grid-cols-2 gap-8 items-center relative">
                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Use next available product ID.</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground">
                                        System product IDs are sequential numbers generated by Finale.
                                    </p>
                                    <p className="text-sm">Next ID: <span className="font-mono">100008</span></p>
                                    <Button className="w-full" onClick={handleCreateWithSystemId}>Use system product ID</Button>
                                </CardContent>
                            </Card>

                            <div className="relative text-center hidden md:block">
                                <span className="text-muted-foreground font-bold text-lg">OR</span>
                            </div>

                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Enter a unique and valid product ID:</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <Input 
                                        placeholder="e.g., SKU-12345" 
                                        value={productId}
                                        onChange={(e) => setProductId(e.target.value)}
                                    />
                                    <Button className="w-full" disabled={!productId.trim()} onClick={handleCreateWithEnteredId}>Use entered product ID</Button>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </main>
            </div>
        </AuthGuard>
    );
}
