'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Calculator } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import AuthGuard from '@/components/auth/auth-guard';

export default function CreateNewAverageCostChangePageContent() {
    const [journalId, setJournalId] = useState('');
    const router = useRouter();

    const handleCreateWithSystemId = () => {
        // In a real app, you'd fetch this from a backend service.
        const systemJournalId = '100002';
        // router.push(`/accounting/average-cost-changes/${systemJournalId}`);
        console.log("Navigating with system ID:", systemJournalId);
    }

    const handleCreateWithEnteredId = () => {
        if (!journalId.trim()) return;
        // router.push(`/accounting/average-cost-changes/${journalId.trim()}`);
        console.log("Navigating with entered ID:", journalId.trim());
    }

    return (
        <AuthGuard>
            <div className="flex flex-col">
                <main className="flex-1 container mx-auto p-4 md:p-8">
                    <div className="flex items-center gap-4 mb-8">
                        <div className="p-3 rounded-lg bg-teal-100 dark:bg-teal-900/50">
                            <Calculator className="w-6 h-6 text-teal-500" />
                        </div>
                        <div>
                             <p className="text-teal-600 dark:text-teal-400 font-semibold">Average cost changes</p>
                             <h1 className="text-2xl font-bold">Create new average cost change</h1>
                        </div>
                    </div>

                    <div className="max-w-4xl mx-auto">
                        <div className="text-center mb-10">
                            <h2 className="text-2xl font-semibold">All average cost changes need a journal entry ID.</h2>
                            <p className="text-muted-foreground mt-1 max-w-2xl mx-auto">Every journal entry ID must be unique. It must be between two and 191 characters. Leading or trailing spaces will be removed. The journal entry ID <span className="font-bold">cannot be changed</span> once assigned.</p>
                        </div>

                        <div className="grid md:grid-cols-2 gap-8 items-center relative">
                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Use next available journal ID.</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground">
                                        System journal IDs are sequential numbers generated by Finale.
                                    </p>
                                    <p className="text-sm">Next ID: <span className="font-mono">100002</span></p>
                                    <Button className="w-full" onClick={handleCreateWithSystemId}>Use system journal ID</Button>
                                </CardContent>
                            </Card>

                            <div className="relative text-center hidden md:block">
                                <span className="text-muted-foreground font-bold text-lg">OR</span>
                            </div>

                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Enter a unique and valid journal ID:</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <Input 
                                        placeholder="" 
                                        value={journalId}
                                        onChange={(e) => setJournalId(e.target.value)}
                                    />
                                    <Button className="w-full" disabled={!journalId.trim()} onClick={handleCreateWithEnteredId}>Use entered journal ID</Button>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </main>
            </div>
        </AuthGuard>
    );
}
