
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Home, ChevronRight, DollarSign } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import AuthGuard from '@/components/auth/auth-guard';

export default function CreateSalesOrderPageContent() {
    const [orderId, setOrderId] = useState('');
    const router = useRouter();

    const handleCreateWithSystemId = () => {
        // In a real app, you'd fetch this from a backend service.
        const systemOrderId = '100500';
        router.push(`/sales/${systemOrderId}`);
    }

    const handleCreateWithEnteredId = () => {
        if (!orderId.trim()) return;
        router.push(`/sales/${orderId.trim()}`);
    }

    return (
        <AuthGuard>
            <div className="flex flex-col">
                <main className="flex-1 container mx-auto p-4 md:p-8">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
                        <Link href="/" className="flex items-center gap-1 hover:text-foreground">
                            <Home className="w-4 h-4" />
                            Home
                        </Link>
                        <ChevronRight className="w-4 h-4" />
                         <Link href="/sales" className="hover:text-foreground">
                            Sales
                        </Link>
                        <ChevronRight className="w-4 h-4" />
                        <span>Create new sale</span>
                    </div>

                    <div className="flex items-center gap-4 mb-8">
                        <div className="bg-green-100 dark:bg-green-900/50 p-3 rounded-lg">
                            <DollarSign className="w-6 h-6 text-green-500" />
                        </div>
                        <div>
                             <p className="text-green-600 dark:text-green-400 font-semibold">Sales</p>
                             <h1 className="text-2xl font-bold">Create new sale</h1>
                        </div>
                    </div>


                    <div className="max-w-4xl mx-auto">
                        <div className="text-center mb-10">
                            <h2 className="text-2xl font-semibold">All sales need an order ID.</h2>
                            <p className="text-muted-foreground mt-1">The order ID must be unique. It must be between two and sixty characters. Leading or trailing spaces will be removed.</p>
                        </div>

                        <div className="grid md:grid-cols-2 gap-8 items-center relative">
                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Use next available order ID.</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground">
                                        System order IDs are sequential numbers generated by Finale.
                                    </p>
                                    <p className="text-sm">Next ID: <span className="font-mono">100500</span></p>
                                    <Button className="w-full" onClick={handleCreateWithSystemId}>Use system order ID</Button>
                                </CardContent>
                            </Card>

                            <div className="relative text-center hidden md:block">
                                <span className="text-muted-foreground font-bold text-lg">OR</span>
                            </div>

                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Enter a unique and valid order ID:</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <Input 
                                        placeholder="" 
                                        value={orderId}
                                        onChange={(e) => setOrderId(e.target.value)}
                                    />
                                    <Button className="w-full" disabled={!orderId.trim()} onClick={handleCreateWithEnteredId}>Use entered order ID</Button>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </main>
            </div>
        </AuthGuard>
    );
}
