
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Home, ChevronRight, RefreshCw } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import AuthGuard from '@/components/auth/auth-guard';

export default function CreateTransferOrderPageContent() {
    const [orderId, setOrderId] = useState('');
    const router = useRouter();

    const handleCreateWithSystemId = () => {
        // In a real app, you'd fetch this from a backend service.
        const systemOrderId = '100505';
        router.push(`/inventory/transfers/${systemOrderId}`);
    }

    const handleCreateWithEnteredId = () => {
        if (!orderId.trim()) return;
        router.push(`/inventory/transfers/${orderId.trim()}`);
    }

    return (
        <AuthGuard>
            <div className="flex flex-col">
                <main className="flex-1 container mx-auto p-4 md:p-8">
                    <div className="flex items-center justify-between mb-8">
                        <div className="flex items-center gap-4">
                            <div className="p-3 rounded-lg bg-purple-100 dark:bg-purple-900/50">
                                <RefreshCw className="w-6 h-6 text-purple-500" />
                            </div>
                            <div>
                                <p className="text-purple-600 dark:text-purple-400 font-semibold">Transfer orders</p>
                                <h1 className="text-2xl font-bold">Create new transfer order</h1>
                            </div>
                        </div>
                        <div>
                             <Button variant="outline">Actions</Button>
                        </div>
                    </div>


                    <div className="max-w-4xl mx-auto">
                        <div className="text-center mb-10">
                            <h2 className="text-2xl font-semibold">All transfer orders need an order ID.</h2>
                            <p className="text-muted-foreground mt-1">The order ID must be unique. It must be between two and sixty characters. Leading or trailing spaces will be removed.</p>
                        </div>

                        <div className="grid md:grid-cols-2 gap-8 items-center relative">
                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Use next available order ID.</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground">
                                        System order IDs are sequential numbers generated by Finale.
                                    </p>
                                    <p className="text-sm">Next ID: <span className="font-mono">100505</span></p>
                                    <Button className="w-full" onClick={handleCreateWithSystemId}>Use system order ID</Button>
                                </CardContent>
                            </Card>

                            <div className="relative text-center hidden md:block">
                                <span className="text-muted-foreground font-bold text-lg">OR</span>
                            </div>

                            <Card className="text-center">
                                <CardHeader>
                                    <CardTitle className="text-lg">Enter a unique and valid order ID:</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <Input 
                                        placeholder="" 
                                        value={orderId}
                                        onChange={(e) => setOrderId(e.target.value)}
                                    />
                                    <Button className="w-full" disabled={!orderId.trim()} onClick={handleCreateWithEnteredId}>Use entered order ID</Button>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </main>
                 <div className="fixed bottom-8 right-8">
                    <Button size="icon" className="rounded-full w-14 h-14 shadow-lg">
                        <MessageCircle className="w-8 h-8" />
                    </Button>
                </div>
            </div>
        </AuthGuard>
    );
}
